# Generated by Django 4.1.7 on 2023-03-16 15:17

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path=pathlib.PurePosixPath('/Users/wrawka/Projects/portfolio-app/projects/img'), verbose_name='Image path'),
        ),
    ]
