# Generated by Django 4.1.7 on 2023-04-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.URLField(blank=True, verbose_name='Source code URL'),
        ),
    ]
